---
session_store_driver: Directory
session_store_config: /etc/fdo/sessions/
ownership_voucher_store_driver: Directory
ownership_voucher_store_config: /etc/fdo/ownership_vouchers/
trusted_device_keys_path: /etc/fdo/keys/device_ca_cert.pem
owner_private_key_path: /etc/fdo/keys/owner_key.der
owner_public_key_path: /etc/fdo/keys/owner_cert.pem
owner_addresses_path: /etc/fdo/owner-addresses.yml
report_to_rendezvous_endpoint_enabled: true
bind: 0.0.0.0:8081
service_info:
 # rhsm_organization_id: 6454383
 # rhsm_activation_key: SDOkey
 # rhsm_run_insights: true
   sshkey_user: root
   sshkey_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDJwfs3RPVkz+PQGvKS/0GKoDivRQufMErxgKYhUO6ll edge@redhat.com"
   files:
     - path: /tmp/run_something.sh
       permissions: 755
       source_path: /files/run_something.sh
   commands:
     - command: bash
       args:
       - /tmp/run_something.sh
       return_stdout: true
       return_stderr: true