kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: manufacturing-sessions
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi 
  storageClassName: ocs-storagecluster-cephfs 
 