---
session_store_driver: Directory
session_store_config: /etc/fdo/sessions/
ownership_voucher_store_driver: Directory
ownership_voucher_store_config: /etc/fdo/ownership_vouchers/
trusted_device_keys_path: /etc/fdo/keys/device_ca_cert.pem
owner_private_key_path: /etc/fdo/keys/owner_key.der
owner_public_key_path: /etc/fdo/keys/owner_cert.pem
owner_addresses:
- transport: HTTP
  port: 8081
  addresses:
    - ip_address: 192.168.1.140
report_to_rendezvous_endpoint_enabled: false
bind: 0.0.0.0:8081
service_info:
  sshkey_user: admin
  sshkey_key: "testkey"